<?php

namespace AppBundle\Repository;

/**
 * DataLoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataLoggerRepository extends \Doctrine\ORM\EntityRepository
{
  public function getDataLoggers($library){
		return $this->createQueryBuilder('dataLogger')
	        ->select('dataLogger')
	        ->innerJoin('dataLogger.room', 'room')
	        ->innerJoin('room.library', 'library')
	        ->where('library = :library')
	        ->setParameter('library', $library)
	        ->getQuery()
	        ->getResult();
	}

  public function getAvgHT($room, $from, $to){
    return $this->createQueryBuilder('d')
          ->select('avg(d.temperature) as meanAvT, avg(d.rh) as meanAvH')
          ->innerJoin('d.room', 'room')
          ->where('room = :room')
          ->andWhere('d.date BETWEEN :from AND :to')
          ->setParameter('from', $from )
          ->setParameter('to', $to)
          ->setParameter('room', $room)
          ->getQuery()
          ->getArrayResult();
  }

  public function getArrayLoads($room){
    return $this->createQueryBuilder('d')
          ->select('d.uniqueAttr')
          ->innerJoin('d.room', 'room')
          ->where('room = :room')
          ->setParameter('room', $room)
          ->getQuery()
          ->getArrayResult();
  }

  public function getDataLoggersValid($room, $from, $to){
    return $this->createQueryBuilder('d')
          ->select('d')
          ->where('d.room = :room')
          ->andWhere('d.enabled = 1')
          ->andWhere('d.date BETWEEN :from AND :to')
          ->setParameter('from', $from )
          ->setParameter('to', $to)
          ->setParameter('room', $room->getId())
          ->getQuery()
          ->getResult();
  }

  public function getLastDate($room){
    return $this->createQueryBuilder('d')
            ->select('d.date')
            ->where('d.room = :room')
            ->andWhere('d.enabled = 1')
            ->setParameter('room', $room->getId())
            ->setMaxResults(1)
            ->orderBy('d.date', 'DESC')
            ->getQuery()
            ->getOneOrNullResult();
    }

  public function getFirstDate($room){
    return $this->createQueryBuilder('d')
            ->select('d.date')
            ->where('d.room = :room')
            ->andWhere('d.enabled = 1')
            ->setParameter('room', $room->getId())
            ->setMaxResults(1)
            ->orderBy('d.date', 'ASC')
            ->getQuery()
            ->getOneOrNullResult();
    }

  public function getDataPersentil($room, $type){
    return $this->createQueryBuilder('d')
            ->select('d.'.$type)
            ->where('d.room = :room')
            ->andwhere('d.enabled = 1')
            ->setParameter('room', $room->getId())
            ->orderBy('d.'.$type, 'ASC')
            ->getQuery()
            ->getScalarResult();
    }

}
