<?php

namespace AppBundle\Repository;

/**
 * DataLoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataLoggerRepository extends \Doctrine\ORM\EntityRepository
{
  public function getDataLoggers($library){
		return $this->createQueryBuilder('dataLogger')
	        ->select('dataLogger')
	        ->innerJoin('dataLogger.room', 'room')
	        ->innerJoin('room.library', 'library')
	        ->where('library = :library')
	        ->setParameter('library', $library)
	        ->getQuery()
	        ->getResult();
	}
}
