<?php

namespace AppBundle\Repository;

/**
 * DataLoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataLoggerRepository extends \Doctrine\ORM\EntityRepository
{
}
