<?php

namespace AppBundle\Repository;

/**
 * SolicitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitationRepository extends \Doctrine\ORM\EntityRepository
{
}
