<?php

namespace AppBundle\Repository;

/**
 * SolicitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitationRepository extends \Doctrine\ORM\EntityRepository
{
  public function getLibrariesFollowings($user)
  {
    return $this->createQueryBuilder('solicitation')
	        ->select('solicitation')
	        ->innerJoin('solicitation.user', 'user')
	        ->where('user = :user and solicitation.state = :state')
	        ->setParameter('user', $user)
          ->setParameter('state', 'accepted')
	        ->getQuery()
	        ->getResult();
  }
}
