<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    function searchByFullname($search) {
        return $this->createQueryBuilder('user')
                    ->select('user')
                    ->where('user.name LIKE :name')
                    ->orWhere('user.lastname LIKE :lastname')
                    ->setParameter('name', '%'.$search.'%')
                    ->setParameter('lastname', '%'.$search.'%')
                    ->getQuery()
                    ->getResult();
    }
}
